#!/usr/bin/env node
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const skillDir = path.dirname(fileURLToPath(import.meta.url))
const skillName = path.basename(skillDir)
const memoryBankPath = path.join(skillDir, 'memory-bank')

if (!fs.existsSync(memoryBankPath)) {
  console.log(`skip ${skillName}: no memory-bank`)
  process.exit(0)
}

const files = fs
  .readdirSync(memoryBankPath, { withFileTypes: true })
  .filter((e) => e.isFile() && e.name.endsWith('.md'))
  .map((e) => e.name)
  .filter((name) => name !== '_template.md')
  .sort()

const indexCandidates = files.filter((name) => /^[A-Z]+\.md$/.test(name))
if (indexCandidates.length === 0) {
  console.log(`skip ${skillName}: no index file`)
  process.exit(0)
}

const indexFile = indexCandidates[0]
const indexPath = path.join(memoryBankPath, indexFile)

const recordFiles = files.filter((name) => name !== indexFile)

const entries = recordFiles.map((file) => {
  const filePath = path.join(memoryBankPath, file)
  const content = fs.readFileSync(filePath, 'utf8')
  const titleMatch = content.match(/^##?\s+(.+)$/m)
  const title = titleMatch ? titleMatch[1].trim() : file.replace('.md', '')
  return `- [${title}](${file})`
})

let existingContent = ''
if (fs.existsSync(indexPath)) {
  existingContent = fs.readFileSync(indexPath, 'utf8')
}

const lines = existingContent.split('\n')
let headerEnd = lines.length
for (let i = 0; i < lines.length; i++) {
  if (/^##\s+/.test(lines[i])) {
    headerEnd = i + 1
    break
  }
}
const header = lines.slice(0, headerEnd).join('\n')

const newContent =
  header +
  '\n\n<!-- The list below is auto-generated by the skill indexer -->\n' +
  (entries.length > 0
    ? entries.join('\n')
    : '_No records yet. Add `.md` files to this folder to populate the index._') +
  '\n'

fs.writeFileSync(indexPath, newContent)
console.log(`updated ${skillName}/${indexFile} (${entries.length} entries)`)
