#!/usr/bin/env node
import fs from 'node:fs'
import path from 'node:path'

// Regenerates EVERY skill's memory-bank index as a Markdown table, for a
// plugin-installed project (where skill bodies no longer live under
// .agents/skills/<name>/, so each skill's own index.mjs is gone).
//
// This duplicates the per-skill indexing logic in skills/coplan/index.mjs
// verbatim (see that file for the column-spec / record-file rules) but
// loops over every skill under .agents/skills/ instead of indexing a
// single skill relative to its own directory.

const MARKER = '<!-- The table below is auto-generated by the skill indexer -->'

const base = path.join(process.cwd(), '.agents', 'skills')

if (!fs.existsSync(base)) {
  console.log('skip: no .agents/skills directory')
  process.exit(0)
}

function parseFrontmatter(content) {
  const match = content.match(/^---\n([\s\S]*?)\n---/)
  if (!match) return {}
  const data = {}
  for (const line of match[1].split('\n')) {
    const m = line.match(/^([A-Za-z0-9_-]+):\s*(.*)$/)
    if (m) data[m[1]] = m[2].trim().replace(/^['"]|['"]$/g, '')
  }
  return data
}

function indexSkill(skillName, memoryBankPath) {
  const allFiles = fs
    .readdirSync(memoryBankPath, { withFileTypes: true })
    .filter((e) => e.isFile() && e.name.endsWith('.md'))
    .map((e) => e.name)
    .sort()

  const indexFile = allFiles.find((name) => /^[A-Z]+\.md$/.test(name))
  if (!indexFile) {
    console.log(`skip ${skillName}: no index file`)
    return
  }

  const indexPath = path.join(memoryBankPath, indexFile)
  const indexContent = fs.readFileSync(indexPath, 'utf8')
  const indexMeta = parseFrontmatter(indexContent)

  const columns = (indexMeta.columns || 'Title=title*')
    .split(',')
    .map((spec) => spec.trim())
    .filter(Boolean)
    .map((spec) => {
      const [label, rawField] = spec.split('=').map((s) => s.trim())
      const link = rawField.endsWith('*')
      return { label, field: link ? rawField.slice(0, -1) : rawField, link }
    })

  const recordFiles = allFiles.filter(
    (name) => name !== indexFile && !name.startsWith('_'),
  )

  const rows = recordFiles.map((file) => {
    const content = fs.readFileSync(path.join(memoryBankPath, file), 'utf8')
    const meta = parseFrontmatter(content)
    const headingMatch = content.match(/^#{1,6}\s+(.+)$/m)
    const fallbackTitle = headingMatch
      ? headingMatch[1].trim()
      : file.replace(/\.md$/, '')
    const cells = columns.map(({ field, link }) => {
      let value = meta[field] || ''
      if (field === 'title' && !value) value = fallbackTitle
      if (link) return `[${value || fallbackTitle}](${file})`
      return value || '—'
    })
    return `| ${cells.join(' | ')} |`
  })

  const table =
    rows.length > 0
      ? [
          `| ${columns.map((c) => c.label).join(' | ')} |`,
          `| ${columns.map(() => '---').join(' | ')} |`,
          ...rows,
        ].join('\n')
      : '_No records yet. Add `.md` files to this folder to populate the index._'

  const markerIdx = indexContent.indexOf(MARKER)
  const head =
    markerIdx !== -1
      ? indexContent.slice(0, markerIdx + MARKER.length)
      : indexContent.replace(/\s*$/, '') + '\n\n' + MARKER

  fs.writeFileSync(indexPath, head + '\n' + table + '\n')
  console.log(`updated ${skillName}/${indexFile} (${rows.length} entries)`)
}

const skillDirs = fs
  .readdirSync(base, { withFileTypes: true })
  .filter((e) => e.isDirectory())
  .map((e) => e.name)
  .sort()

for (const skillName of skillDirs) {
  const memoryBankPath = path.join(base, skillName, 'memory-bank')
  if (!fs.existsSync(memoryBankPath)) continue
  indexSkill(skillName, memoryBankPath)
}
