#!/usr/bin/env node
import fs from 'node:fs'
import path from 'node:path'

const skillsRoot = path.join(process.cwd(), 'skills')

for (const entry of fs.readdirSync(skillsRoot, { withFileTypes: true })) {
  if (!entry.isDirectory()) continue

  const skillName = entry.name
  const skillPath = path.join(skillsRoot, skillName)
  const memoryBankPath = path.join(skillPath, 'memory-bank')

  if (!fs.existsSync(memoryBankPath)) continue

  const files = fs
    .readdirSync(memoryBankPath, { withFileTypes: true })
    .filter((e) => e.isFile() && e.name.endsWith('.md'))
    .map((e) => e.name)
    .filter((name) => name !== '_template.md')
    .sort()

  // Determine the index file name (usually matches the section, e.g., PLAN.md, ANALYSIS.md)
  const indexCandidates = files.filter((name) =>
    /^[A-Z]+\.md$/.test(name),
  )
  if (indexCandidates.length === 0) continue

  const indexFile = indexCandidates[0]
  const indexPath = path.join(memoryBankPath, indexFile)

  // Collect entries from other .md files in the same folder
  const recordFiles = files.filter((name) => name !== indexFile)

  const entries = recordFiles.map((file) => {
    const filePath = path.join(memoryBankPath, file)
    const content = fs.readFileSync(filePath, 'utf8')
    const titleMatch = content.match(/^##?\s+(.+)$/m)
    const title = titleMatch ? titleMatch[1].trim() : file.replace('.md', '')
    return `- [${title}](${file})`
  })

  // Read existing index file to preserve header/intro
  let existingContent = ''
  if (fs.existsSync(indexPath)) {
    existingContent = fs.readFileSync(indexPath, 'utf8')
  }

  // Find the section heading line (e.g., "## Plans", "## Analyses")
  const lines = existingContent.split('\n')
  let headerEnd = lines.length
  for (let i = 0; i < lines.length; i++) {
    if (/^##\s+/.test(lines[i])) {
      headerEnd = i + 1
      break
    }
  }
  const header = lines.slice(0, headerEnd).join('\n')

  const newContent =
    header +
    '\n\n<!-- The list below is auto-generated by npm run update-indices -->\n' +
    (entries.length > 0
      ? entries.join('\n')
      : '_No records yet. Add `.md` files to this folder to populate the index._') +
    '\n'

  fs.writeFileSync(indexPath, newContent)
  console.log(`updated ${path.join(skillName, 'memory-bank', indexFile)} (${entries.length} entries)`)
}

console.log('Done.')
