#!/usr/bin/env node
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

// Regenerates a skill's memory-bank index as a Markdown table.
//
// - The index file is the first ALL-CAPS file in memory-bank/ (e.g. PLAN.md).
//   Its frontmatter declares the table columns:
//       ---
//       columns: Date=date, Plan=title*, Status=status
//       ---
//   Each `Label=field` maps a column header to a record's frontmatter field.
//   A trailing `*` marks the column rendered as a link to the record file.
// - Records are every other .md file not starting with `_` (so `_template.md`
//   and similar helper files are ignored).
//   Column values come from each record's flat frontmatter; the `title` field
//   falls back to the first heading, then the filename.

const MARKER = '<!-- The table below is auto-generated by the skill indexer -->'

const skillDir = path.dirname(fileURLToPath(import.meta.url))
const skillName = path.basename(skillDir)
const memoryBankPath = path.join(skillDir, 'memory-bank')

if (!fs.existsSync(memoryBankPath)) {
  console.log(`skip ${skillName}: no memory-bank`)
  process.exit(0)
}

function parseFrontmatter(content) {
  const match = content.match(/^---\n([\s\S]*?)\n---/)
  if (!match) return {}
  const data = {}
  for (const line of match[1].split('\n')) {
    const m = line.match(/^([A-Za-z0-9_-]+):\s*(.*)$/)
    if (m) data[m[1]] = m[2].trim().replace(/^['"]|['"]$/g, '')
  }
  return data
}

const allFiles = fs
  .readdirSync(memoryBankPath, { withFileTypes: true })
  .filter((e) => e.isFile() && e.name.endsWith('.md'))
  .map((e) => e.name)
  .sort()

const indexFile = allFiles.find((name) => /^[A-Z]+\.md$/.test(name))
if (!indexFile) {
  console.log(`skip ${skillName}: no index file`)
  process.exit(0)
}

const indexPath = path.join(memoryBankPath, indexFile)
const indexContent = fs.readFileSync(indexPath, 'utf8')
const indexMeta = parseFrontmatter(indexContent)

const columns = (indexMeta.columns || 'Title=title*')
  .split(',')
  .map((spec) => spec.trim())
  .filter(Boolean)
  .map((spec) => {
    const [label, rawField] = spec.split('=').map((s) => s.trim())
    const link = rawField.endsWith('*')
    return { label, field: link ? rawField.slice(0, -1) : rawField, link }
  })

const recordFiles = allFiles.filter(
  (name) => name !== indexFile && !name.startsWith('_'),
)

const rows = recordFiles.map((file) => {
  const content = fs.readFileSync(path.join(memoryBankPath, file), 'utf8')
  const meta = parseFrontmatter(content)
  const headingMatch = content.match(/^#{1,6}\s+(.+)$/m)
  const fallbackTitle = headingMatch
    ? headingMatch[1].trim()
    : file.replace(/\.md$/, '')
  const cells = columns.map(({ field, link }) => {
    let value = meta[field] || ''
    if (field === 'title' && !value) value = fallbackTitle
    if (link) return `[${value || fallbackTitle}](${file})`
    return value || '—'
  })
  return `| ${cells.join(' | ')} |`
})

const table =
  rows.length > 0
    ? [
        `| ${columns.map((c) => c.label).join(' | ')} |`,
        `| ${columns.map(() => '---').join(' | ')} |`,
        ...rows,
      ].join('\n')
    : '_No records yet. Add `.md` files to this folder to populate the index._'

const markerIdx = indexContent.indexOf(MARKER)
const head =
  markerIdx !== -1
    ? indexContent.slice(0, markerIdx + MARKER.length)
    : indexContent.replace(/\s*$/, '') + '\n\n' + MARKER

fs.writeFileSync(indexPath, head + '\n' + table + '\n')
console.log(`updated ${skillName}/${indexFile} (${rows.length} entries)`)
